export const flags = {
    "Canada": "https://flagcdn.com/16x12/ca.webp",
    "United States": "https://flagcdn.com/16x12/us.webp",
    "Mexico": "https://flagcdn.com/16x12/mx.webp",
    "Ireland": "https://flagcdn.com/16x12/ie.webp",
    "Spain": "https://flagcdn.com/16x12/es.webp",
    "United Kingdom": "https://flagcdn.com/16x12/gb.webp",
    "France": "https://flagcdn.com/16x12/fr.webp",
    "Belgium": "https://flagcdn.com/16x12/be.webp",
    "Netherlands": "https://flagcdn.com/16x12/nl.webp",
    "Germany": "https://flagcdn.com/16x12/de.webp",
    "Italy": "https://flagcdn.com/16x12/it.webp",
    "Sweden": "https://flagcdn.com/16x12/se.webp",
    "South Africa": "https://flagcdn.com/16x12/za.webp",
    "Poland": "https://flagcdn.com/16x12/pl.webp",
    "Egypt": "https://flagcdn.com/16x12/eg.webp",
    "Turkey": "https://flagcdn.com/16x12/tr.webp",
    "Saudi Arabia": "https://flagcdn.com/16x12/sa.webp",
    "United Arab Emirates": "https://flagcdn.com/16x12/ae.webp",
    "India": "https://flagcdn.com/16x12/in.webp",
    "Singapore": "https://flagcdn.com/16x12/sg.webp",
    "Japan": "https://flagcdn.com/16x12/jp.webp",
    "Australia": "https://flagcdn.com/16x12/au.webp"
}